version: "3.7"

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres:11.7
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: housinghub
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppassword
    ports:
      - 5431:5432

  housinghub-backend:
    image: codeforcharlottesville/housinghub:latest
    ports:
      - 5000:5000
    environment:
      DB_HOST: postgres
      DB_USER: app
      DB_PASSWORD: apppassword
      TOKEN_SECRET_KEY_ROTATION_SECONDS: 172800
      TOKEN_EXP_SECONDS: 300